<?php
$data = array (
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '耳机音箱与存储卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '101',
    'name' => '耳机音箱与存储卡',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '小米活塞耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '103',
    'name' => '小米活塞耳机',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '存储卡',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '107',
    'name' => '存储卡',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '小米蓝牙耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '104',
    'name' => '小米蓝牙耳机',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '小米头戴式耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '102',
    'name' => '小米头戴式耳机',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '音箱',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '106',
    'name' => '音箱',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '品牌耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '105',
    'name' => '品牌耳机',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '保护套与贴膜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '108',
    'name' => '保护套与贴膜',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '防尘塞',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '111',
    'name' => '防尘塞',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '翻盖保护套',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '127',
    'name' => '翻盖保护套',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '软胶保护套',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '128',
    'name' => '软胶保护套',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '保护套',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '109',
    'name' => '保护套',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '保护壳',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '129',
    'name' => '保护壳',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '贴膜',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '110',
    'name' => '贴膜',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '购买手机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '69',
    'name' => '购买手机',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '小米手机4',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '71',
    'name' => '小米手机4',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '红米Note',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '73',
    'name' => '红米Note',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '根据机型选配件',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '75',
    'name' => '根据机型选配件',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '红米手机2',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '72',
    'name' => '红米手机2',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '小米Note',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '70',
    'name' => '小米Note',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '合约机',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '74',
    'name' => '合约机',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '路由器与智能硬件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => 0,
    'level' => 0,
    'id' => '80',
    'name' => '路由器与智能硬件',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '小米路由器mini',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '82',
    'name' => '小米路由器mini',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '87',
    'name' => '血压计',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '体重秤',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '90',
    'name' => '体重秤',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '床头灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => '床头灯',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '智能插座',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '88',
    'name' => '智能插座',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '运动相机',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '85',
    'name' => '运动相机',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '小米路由器',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '81',
    'name' => '小米路由器',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '随身WiFi',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '92',
    'name' => '随身WiFi',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '小米手环',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '83',
    'name' => '小米手环',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '智能灯泡',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '智能灯泡',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '摄像机',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '86',
    'name' => '摄像机',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '智能家庭套装',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '93',
    'name' => '智能家庭套装',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '净化器与滤芯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '84',
    'name' => '净化器与滤芯',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '小米生活方式',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '118',
    'name' => '小米生活方式',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '生活周边',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '123',
    'name' => '生活周边',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '米兔',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '120',
    'name' => '米兔',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '酷玩产品',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '130',
    'name' => '酷玩产品',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '背包',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '121',
    'name' => '背包',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '卫衣',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '131',
    'name' => '卫衣',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '小米鼠标垫',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '122',
    'name' => '小米鼠标垫',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '119',
    'name' => 'T恤',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '132',
    'name' => 'POLO衫',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '插线板、移动电源与电池',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '94',
    'name' => '插线板、移动电源与电池',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '品牌移动电源',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '97',
    'name' => '品牌移动电源',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '99',
    'name' => '充电器',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '小米移动电源',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '95',
    'name' => '小米移动电源',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '插线板',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '96',
    'name' => '插线板',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '线材',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '100',
    'name' => '线材',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '98',
    'name' => '电池',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '后盖与个性化配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '112',
    'name' => '后盖与个性化配件',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '耳机绕线器',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '117',
    'name' => '耳机绕线器',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '后盖',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '114',
    'name' => '后盖',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '贴纸',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '115',
    'name' => '贴纸',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '手机支架',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '116',
    'name' => '手机支架',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '米键',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '米键',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '购买电视与平板',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '9',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '2',
    'level' => 0,
    'id' => '76',
    'name' => '购买电视与平板',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '小米平板',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '79',
    'name' => '小米平板',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '小米电视2',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '77',
    'name' => '小米电视2',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '小米盒子',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '78',
    'name' => '小米盒子',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '小米电视',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '124',
    'name' => '小米电视',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '电视盒子配件',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '125',
    'name' => '电视盒子配件',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '小米盒子mini',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '126',
    'name' => '小米盒子mini',
  ),
);
?>