<?php
$data = array (
  0 => 
  array (
    'cat_id' => '101',
    'cat_name' => '耳机音箱与存储卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '108',
    'cat_name' => '保护套与贴膜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '69',
    'cat_name' => '购买手机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '80',
    'cat_name' => '路由器与智能硬件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '118',
    'cat_name' => '小米生活方式',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '94',
    'cat_name' => '插线板、移动电源与电池',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '112',
    'cat_name' => '后盖与个性化配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '76',
    'cat_name' => '购买电视与平板',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '9',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '2',
  ),
  8 => 
  array (
    'cat_id' => '71',
    'cat_name' => '小米手机4',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  9 => 
  array (
    'cat_id' => '73',
    'cat_name' => '红米Note',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  10 => 
  array (
    'cat_id' => '75',
    'cat_name' => '根据机型选配件',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  11 => 
  array (
    'cat_id' => '72',
    'cat_name' => '红米手机2',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  12 => 
  array (
    'cat_id' => '70',
    'cat_name' => '小米Note',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  13 => 
  array (
    'cat_id' => '74',
    'cat_name' => '合约机',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  14 => 
  array (
    'cat_id' => '79',
    'cat_name' => '小米平板',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  15 => 
  array (
    'cat_id' => '77',
    'cat_name' => '小米电视2',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  16 => 
  array (
    'cat_id' => '78',
    'cat_name' => '小米盒子',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  17 => 
  array (
    'cat_id' => '124',
    'cat_name' => '小米电视',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  18 => 
  array (
    'cat_id' => '125',
    'cat_name' => '电视盒子配件',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  19 => 
  array (
    'cat_id' => '126',
    'cat_name' => '小米盒子mini',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  20 => 
  array (
    'cat_id' => '82',
    'cat_name' => '小米路由器mini',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  21 => 
  array (
    'cat_id' => '87',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  22 => 
  array (
    'cat_id' => '90',
    'cat_name' => '体重秤',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  23 => 
  array (
    'cat_id' => '91',
    'cat_name' => '床头灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '88',
    'cat_name' => '智能插座',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  25 => 
  array (
    'cat_id' => '85',
    'cat_name' => '运动相机',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  26 => 
  array (
    'cat_id' => '81',
    'cat_name' => '小米路由器',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  27 => 
  array (
    'cat_id' => '92',
    'cat_name' => '随身WiFi',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  28 => 
  array (
    'cat_id' => '83',
    'cat_name' => '小米手环',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  29 => 
  array (
    'cat_id' => '89',
    'cat_name' => '智能灯泡',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '86',
    'cat_name' => '摄像机',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  31 => 
  array (
    'cat_id' => '93',
    'cat_name' => '智能家庭套装',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  32 => 
  array (
    'cat_id' => '84',
    'cat_name' => '净化器与滤芯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  33 => 
  array (
    'cat_id' => '97',
    'cat_name' => '品牌移动电源',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  34 => 
  array (
    'cat_id' => '99',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '95',
    'cat_name' => '小米移动电源',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  36 => 
  array (
    'cat_id' => '96',
    'cat_name' => '插线板',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '100',
    'cat_name' => '线材',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  38 => 
  array (
    'cat_id' => '98',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  39 => 
  array (
    'cat_id' => '103',
    'cat_name' => '小米活塞耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  40 => 
  array (
    'cat_id' => '107',
    'cat_name' => '存储卡',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  41 => 
  array (
    'cat_id' => '104',
    'cat_name' => '小米蓝牙耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  42 => 
  array (
    'cat_id' => '102',
    'cat_name' => '小米头戴式耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  43 => 
  array (
    'cat_id' => '106',
    'cat_name' => '音箱',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  44 => 
  array (
    'cat_id' => '105',
    'cat_name' => '品牌耳机',
    'measure_unit' => '',
    'parent_id' => '101',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  45 => 
  array (
    'cat_id' => '111',
    'cat_name' => '防尘塞',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  46 => 
  array (
    'cat_id' => '127',
    'cat_name' => '翻盖保护套',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  47 => 
  array (
    'cat_id' => '128',
    'cat_name' => '软胶保护套',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  48 => 
  array (
    'cat_id' => '109',
    'cat_name' => '保护套',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  49 => 
  array (
    'cat_id' => '129',
    'cat_name' => '保护壳',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  50 => 
  array (
    'cat_id' => '110',
    'cat_name' => '贴膜',
    'measure_unit' => '',
    'parent_id' => '108',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  51 => 
  array (
    'cat_id' => '117',
    'cat_name' => '耳机绕线器',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '114',
    'cat_name' => '后盖',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  53 => 
  array (
    'cat_id' => '115',
    'cat_name' => '贴纸',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '116',
    'cat_name' => '手机支架',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '113',
    'cat_name' => '米键',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '123',
    'cat_name' => '生活周边',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  57 => 
  array (
    'cat_id' => '120',
    'cat_name' => '米兔',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  58 => 
  array (
    'cat_id' => '130',
    'cat_name' => '酷玩产品',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  59 => 
  array (
    'cat_id' => '121',
    'cat_name' => '背包',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  60 => 
  array (
    'cat_id' => '131',
    'cat_name' => '卫衣',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '122',
    'cat_name' => '小米鼠标垫',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  62 => 
  array (
    'cat_id' => '119',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  63 => 
  array (
    'cat_id' => '132',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>